# Generated by Django 2.2.6 on 2020-03-20 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='isActive',
            new_name='IsActive',
        ),
    ]
